# Generated by Django 3.2.14 on 2022-08-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeshnyavki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeshnyavkа',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smeshnyavki.category', verbose_name='Категория котика'),
        ),
    ]
