# Generated by Django 3.2.14 on 2022-08-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeshnyavki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='smeshnyavkа',
            name='categ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smeshnyavki.category'),
        ),
    ]
